using System.CodeDom.Compiler;

namespace BerryUI.FNA.FreeType;

[NativeTypeName("unsigned int")]
[GeneratedCode("ClangSharp", "22.1.8.0")]
public enum FT_PaintFormat : uint
{
    PAINTFORMAT_COLR_LAYERS = 1,
    PAINTFORMAT_SOLID = 2,
    PAINTFORMAT_LINEAR_GRADIENT = 4,
    PAINTFORMAT_RADIAL_GRADIENT = 6,
    PAINTFORMAT_SWEEP_GRADIENT = 8,
    PAINTFORMAT_GLYPH = 10,
    PAINTFORMAT_COLR_GLYPH = 11,
    PAINTFORMAT_TRANSFORM = 12,
    PAINTFORMAT_TRANSLATE = 14,
    PAINTFORMAT_SCALE = 16,
    PAINTFORMAT_ROTATE = 24,
    PAINTFORMAT_SKEW = 28,
    PAINTFORMAT_COMPOSITE = 32,
    PAINT_FORMAT_MAX = 33,
    PAINTFORMAT_UNSUPPORTED = 255,
}
