<Project Sdk="Microsoft.NET.Sdk" InitialTargets="ValidateFNALibs">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <!-- Only compile our own sources -->
        <Compile Remove="**"/>
        <Compile Include=".\*.cs"/>
        <Compile Include=".\FreeType\*.cs"/>
        
        <!-- Include required content (except for shader sources) -->
        <Content Include="Assets\**" CopyToOutputDirectory="PreserveNewest"/>
        <Content Remove="Assets\**\*.fx"/>

        <ProjectReference Include="..\BerryUI\BerryUI.csproj"/>
        <ProjectReference Include="..\BerryUI.SourceGen\BerryUI.SourceGen.csproj" OutputItemType="Analyzer" Private="false" PrivateAssets="All"/>
        <Compile Include="..\BerryUI\GlobalUsings.cs"/>

        <ProjectReference Include="FNA\FNA.Core.csproj"/>
        <Content Include="runtimes\**" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <Target Name="ValidateFNALibs">
        <Error
            Condition="!Exists('runtimes')"
            Text="'runtimes' directory not found! Run './fetch-fnalibs.sh' to download the latest native libraries."/>
    </Target>

    <Target Name="GenerateDebugBuildInfo" Condition="'$(Configuration)' == 'Debug'" BeforeTargets="BeforeCompile">
        <PropertyGroup>
            <DebugBuildInfoCode>
                <![CDATA[
namespace BerryUI.FNA;

public static class DebugBuildInfo
{
    public const string ProjectPath = "$(MSBuildProjectDirectory)";
}
                ]]>
            </DebugBuildInfoCode>
        </PropertyGroup>

        <WriteLinesToFile
            File="$(IntermediateOutputPath)DebugBuildInfo.g.cs"
            Lines="$([MSBuild]::Escape($(DebugBuildInfoCode)))"
            Overwrite="true" />

        <ItemGroup>
            <Compile Include="$(IntermediateOutputPath)DebugBuildInfo.g.cs" />
        </ItemGroup>
    </Target>
    
    <PropertyGroup>
        <!-- Zig doesn't need separate -musl variants; it's libc is fully static -->
        <_ZigToolsetPackageName>Vezel.Zig.Toolsets.$([System.String]::Copy($(NETCoreSdkPortableRuntimeIdentifier)).Replace('-musl', ''))</_ZigToolsetPackageName>
        <_ZigToolsetPackageVersion>0.16.0.2</_ZigToolsetPackageVersion>

        <_ZigToolsetPackageNameLower>$([System.String]::Copy($(_ZigToolsetPackageName)).ToLowerInvariant())</_ZigToolsetPackageNameLower>
        <_ZigToolsetPackageRoot>$([MSBuild]::NormalizePath('$(NuGetPackageRoot)', '$(_ZigToolsetPackageNameLower)', '$(_ZigToolsetPackageVersion)'))</_ZigToolsetPackageRoot>
        <_ZigToolsetPropsPath>$([MSBuild]::NormalizePath('$(_ZigToolsetPackageRoot)', 'build', '$(_ZigToolsetPackageName).props'))</_ZigToolsetPropsPath>
    </PropertyGroup>

    <!-- Grab the Zig SDK for the current platform -->
    <ItemGroup>
        <!-- Need PackageDownload so that it doesn't appear in the lock file (since this changes based on the host) -->
        <PackageDownload Include="$(_ZigToolsetPackageName)" Version="[$(_ZigToolsetPackageVersion)]" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="native\zig-out\lib\" />
    </ItemGroup>
    <ItemGroup>
      <ClCompile Include="Assets\BerryUI.FNA\Effects\Glyph.fx" />
      <ClCompile Include="Assets\BerryUI.FNA\Effects\Sprite.fx" />
    </ItemGroup>

    <Import Project="$(_ZigToolsetPropsPath)" Condition="Exists($(_ZigToolsetPropsPath))" />

    <Target Name="CompileNativeLibraries" AfterTargets="Build">
        <Exec Command="&quot;$(ZigExePath)&quot; build all" ConsoleToMSBuild="true" WorkingDirectory="$(MSBuildThisFileDirectory)native"/>
    </Target>

</Project>
