<Project Sdk="Microsoft.NET.Sdk" InitialTargets="ValidateFNALibs">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BerryUI\BerryUI.csproj"/>
        <Compile Include="..\BerryUI\GlobalUsings.cs"/>

        <ProjectReference Include="FNA\FNA.Core.csproj"/>
        <Compile Remove="FNA\**"/>
        <Content Include="runtimes\**" CopyToOutputDirectory="PreserveNewest"/>

        <ProjectReference Include="FontStashSharp\src\XNA\FontStashSharp.FNA.Core.csproj"/>
        <Compile Remove="FontStashSharp\**"/>
    </ItemGroup>

    <Target Name="ValidateFNALibs">
        <Error
            Condition="!Exists('runtimes')"
            Text="'runtimes' directory not found! Run './fetch-fnalibs.sh' to download the latest native libraries."/>
    </Target>

</Project>
