<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\" />

        <ProjectReference Include="..\BerryUI.SourceGen\BerryUI.SourceGen.csproj" OutputItemType="Analyzer" Private="false" PrivateAssets="All"/>
    </ItemGroup>

</Project>
