using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;

namespace BerryUI.SourceGen;

#pragma warning disable CS9113 // Parameter is unread.

/// Declares that this struct contains bit-packed fields.
[AttributeUsage(AttributeTargets.Struct)]
public class BitpackedAttribute(uint bitSize) : Attribute;

/// Specifies the bit-size of the current field.
[AttributeUsage(AttributeTargets.Property)]
public class BitfieldSizeAttribute(uint bitSize) : Attribute;

#pragma warning restore CS9113 // Parameter is unread.

[Generator]
public class BitfieldGenerator : IIncrementalGenerator {
    private const string BitpackedAttributeName = $"BerryUI.SourceGen.{nameof(BitpackedAttribute)}";
    private const string BitfieldSizeAttributeName = $"BerryUI.SourceGen.{nameof(BitfieldSizeAttribute)}";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var sources = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                BitpackedAttributeName,
                predicate: IsSyntaxTargetForGeneration,
                transform: GetSemanticTargetForGeneration)
            .Collect();

        context.RegisterSourceOutput(sources, static (context, sources) => {
            using var sw = new StringWriter();
            using var writer = new IndentedTextWriter(sw);

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System.Runtime.InteropServices;");
            writer.WriteLine("using System.Runtime.CompilerServices;");
            writer.WriteLine();

            foreach (var source in sources) {
                uint fieldSize = 0;
                foreach (var p in source.Fields) {
                    fieldSize += p.Size;
                }

                if (fieldSize != source.Size) {
                    context.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor(
                        id: "BERRYUI0002",
                        title: "Incorrect Bitfield size",
                        description: "The sum of the fields does not equal the size of the bitfield.",
                        messageFormat: "The sum of the fields ({0}) must equal size of containing bitfield struct ({1})",
                        category: "Usage",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true
                    ), source.Location, fieldSize, source.Size));
                }

                Generate(source, writer);
            }

            context.AddSource("Bitfields.g.cs", sw.ToString());
        });
    }

    private readonly struct Definition(TypeDefinition sourceType, uint size, Definition.Field[] fields, Location location) : IEquatable<Definition> {
        public readonly struct Field(string type, string name, string modifiers, uint size) : IEquatable<Field> {
            public readonly string Type = type;
            public readonly string Name = name;
            public readonly string Modifiers = modifiers;
            public readonly uint Size = size;

            public bool Equals(Field other) =>
                other.Type.Equals(Type) &&
                other.Modifiers.Equals(Modifiers) &&
                other.Size.Equals(Size);
        }

        public readonly TypeDefinition SourceType = sourceType;
        public readonly uint Size = size;
        public readonly Field[] Fields = fields;

        public readonly Location Location = location;

        public bool Equals(Definition other) =>
            other.SourceType.Equals(SourceType) &&
            other.Size.Equals(Size) &&
            other.Fields.SequenceEqual(Fields);
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken ct) {
        return node is StructDeclarationSyntax ||
               node is RecordDeclarationSyntax record && record.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword);
    }

    private static Definition GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
        var typeDecl = (TypeDeclarationSyntax)ctx.TargetNode;
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        return new Definition(
            sourceType: TypeDefinition.FromSymbol(typeSymbol, typeDecl),
            size: ctx.Attributes
                .Where(arg =>
                    arg.AttributeClass?.Name == nameof(BitpackedAttribute) &&
                    arg.AttributeClass?.ToDisplayString() == BitpackedAttributeName)
                .Select(arg => (uint)arg.ConstructorArguments[0].Value!)
                .First(),
            fields: typeSymbol
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Select(property => {
                    var sizeAttr = property
                        .GetAttributes()
                        .FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == BitfieldSizeAttributeName);
                    if (sizeAttr == null) {
                        return new Definition.Field("", "", "", 0);
                    }

                    uint size = (uint)sizeAttr.ConstructorArguments[0].Value!;

                    string modifiers = "";
                    var propertyDecl = (PropertyDeclarationSyntax?)property.DeclaringSyntaxReferences
                        .Select(r => r.GetSyntax(ct))
                        .FirstOrDefault(n => n is PropertyDeclarationSyntax);
                    if (propertyDecl is not null) {
                        modifiers = string.Join(" ", propertyDecl.Modifiers
                            .Where(t => !t.IsKind(SyntaxKind.PartialKeyword))
                            .Select(t => t.Text));
                    }

                    return new Definition.Field(
                        type: property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        property.Name,
                        modifiers,
                        size);
                })
                .Where(def => !string.IsNullOrEmpty(def.Type))
                .ToArray(),
            location: typeSymbol.Locations[0]
        );
    }

    private static void Generate(Definition def, IndentedTextWriter writer) {
        // Emit the namespace.
        if (!string.IsNullOrWhiteSpace(def.SourceType.Namespace)) {
            writer.WriteLine($"namespace {def.SourceType.Namespace} {{");
            writer.Indent++;
        }

        // Emit containing types.
        var parentClasses = new Stack<string>();
        var parent = def.SourceType.Parent;
        while (parent is not null) {
            parentClasses.Push($"partial {parent.Keyword} {parent.Name} {{");
            parent = parent.Parent;
        }

        while (parentClasses.Count != 0) {
            writer.WriteLine(parentClasses.Pop());
            writer.Indent++;
        }

        // Emit the type definition
        writer.WriteLine($"{(def.SourceType.IsReadonly ? "readonly " : "")}partial {def.SourceType.Keyword} {def.SourceType.Name} : System.IEquatable<{def.SourceType.Name}> {{");
        writer.Indent++;

        const uint maxBackingSize = 64;

        // Emit the backing value(s)
        var fieldVarOffsets = new List<(uint Shift, uint Size, uint ValueIdx)>[def.Fields.Length];
        var valueBitSizes = new List<uint>();
        string fieldModifiers = def.SourceType.IsReadonly ? "readonly " : "";

        int currFlushIdx = 0;
        uint currFieldSize = 0;
        uint valueIdx = 0;
        uint localOffset = 0;
        for (int fieldIdx = 0; fieldIdx < def.Fields.Length; fieldIdx++) {
            var field = def.Fields[fieldIdx];
            currFieldSize += field.Size;

            string? typeName = currFieldSize switch {
                8 => "byte",
                16 => "ushort",
                32 => "uint",
                64 => "ulong",
                _ => null
            };
            if (typeName != null) {
                for (; currFlushIdx <= fieldIdx; currFlushIdx++) {
                    fieldVarOffsets[currFlushIdx] = [(Shift: localOffset, def.Fields[currFlushIdx].Size, ValueIdx: valueIdx)];
                    localOffset += def.Fields[currFlushIdx].Size;
                }

                valueBitSizes.Add(currFieldSize);

                currFieldSize = 0;
                localOffset = 0;
                writer.WriteLine($"private {fieldModifiers}{typeName} __value{valueIdx++};");
            } else if (currFieldSize > maxBackingSize) {
                for (; currFlushIdx < fieldIdx; currFlushIdx++) {
                    fieldVarOffsets[currFlushIdx] = [(Shift: localOffset, def.Fields[currFlushIdx].Size, ValueIdx: valueIdx)];
                    localOffset += def.Fields[currFlushIdx].Size;
                }

                valueBitSizes.Add(maxBackingSize);

                currFieldSize -= maxBackingSize;
                fieldVarOffsets[currFlushIdx++] = [
                    (Shift: localOffset, maxBackingSize - localOffset, ValueIdx: valueIdx),
                    (Shift: 0, Size: currFieldSize, ValueIdx: valueIdx),
                ];
                localOffset = currFieldSize;

                writer.WriteLine($"private {fieldModifiers}ulong __value{valueIdx++};");
            }
        }

        if (currFieldSize > 0) {
            for (; currFlushIdx < def.Fields.Length; currFlushIdx++) {
                fieldVarOffsets[currFlushIdx] = [(Shift: localOffset, def.Fields[currFlushIdx].Size, ValueIdx: valueIdx)];
                localOffset += def.Fields[currFlushIdx].Size;
            }

            string typeName;
            if (currFieldSize > 32) {
                typeName = "ulong";
                valueBitSizes.Add(64);
            } else if (currFieldSize > 16) {
                typeName = "uint";
                valueBitSizes.Add(32);
            } else if (currFieldSize > 8) {
                typeName = "ushort";
                valueBitSizes.Add(16);
            } else {
                typeName = "byte";
                valueBitSizes.Add(8);
            }

            writer.WriteLine($"private {fieldModifiers}{typeName} __value{valueIdx}");
        }

        // Complete the partial property definitions
        for (int i = 0; i < def.Fields.Length; i++) {
            var field = def.Fields[i];
            var fieldOffsets = fieldVarOffsets[i];

            writer.WriteLine();
            writer.WriteLine($"{field.Modifiers} partial {field.Type} {field.Name} {{");
            writer.Indent++;

            writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            writer.WriteLine("get {");
            writer.Indent++;

            uint valueShift = 0;
            for (int offIdx = 0; offIdx < fieldOffsets.Count; offIdx++) {
                writer.Write(offIdx == 0
                    ? $"return unchecked(({field.Type})("
                    : " |\n       ");

                var off = fieldOffsets[offIdx];
                uint mask = (1u << (int)off.Size) - 1u;
                uint typeMax = (1u << (int)(valueBitSizes[(int)off.ValueIdx] - off.Shift)) - 1u;
                writer.Write($"(((__value{off.ValueIdx}{(off.Shift > 0 ? $" >> {off.Shift}" : "")}){(mask != typeMax ? $" & 0x{mask:x}" : "")}){(valueShift > 0 ? $" << {valueShift}" : "")})");
                valueShift += off.Size;
            }

            writer.WriteLine("));");

            writer.Indent--;
            writer.WriteLine("}");

            if (!def.SourceType.IsReadonly) {
                writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
                writer.WriteLine("set {");
                writer.Indent++;

                writer.WriteLine($"System.Diagnostics.Debug.Assert(value <= 0x{(1u << (int)field.Size) - 1u:x}, \"Field '{field.Name}' is outside its defined bit-size\");");

                valueShift = 0;
                foreach (var off in fieldOffsets) {
                    uint writeMask = ~(((1u << (int)off.Size) - 1u) << (int)off.Shift);
                    uint readMask = ((1u << (int)off.Size) - 1u) << (int)valueShift;
                    uint typeMax = (1u << (int)valueBitSizes[(int)off.ValueIdx]) - 1u;
                    writer.WriteLine($"__value{off.ValueIdx} = {(writeMask != 0 ? $"(__value{off.ValueIdx} & 0x{writeMask:x}) | " : "")}((unchecked(({GetTypeForSize(field.Size)})value){(readMask != typeMax ? $" & 0x{readMask:x}" : "")}){(off.Shift > 0 ? $" << {off.Shift}" : "")});");
                    valueShift += off.Size;
                }

                writer.Indent--;
                writer.WriteLine("}");
            }

            writer.Indent--;
            writer.WriteLine("}");
        }

        // Create a constructor
        {
            writer.WriteLine();
            writer.Write($"public {def.SourceType.Name}(");
            for (int i = 0; i < def.Fields.Length; i++) {
                var field = def.Fields[i];
                if (i > 0) {
                    writer.Write(", ");
                }

                writer.Write($"{field.Type} p{field.Name}");
            }

            writer.WriteLine(") {");
            writer.Indent++;

            uint lastValueIdx = uint.MaxValue;
            foreach (var field in def.Fields) {
                writer.WriteLine($"System.Diagnostics.Debug.Assert(unchecked(({GetTypeForSize(field.Size)})p{field.Name}) <= 0x{(1u << (int)field.Size) - 1u:x}, \"Field '{field.Name}' is outside its defined bit-size\");");
            }



            for (int i = 0; i < def.Fields.Length; i++) {
                var field = def.Fields[i];
                var fieldOffsets = fieldVarOffsets[i];

                uint valueShift = 0;
                foreach (var off in fieldOffsets) {
                    uint readMask = ((1u << (int)off.Size) - 1u) << (int)valueShift;
                    uint typeMax = (1u << (int)valueBitSizes[(int)off.ValueIdx]) - 1u;

                    if (lastValueIdx == uint.MaxValue) {
                        writer.Write($"__value{off.ValueIdx} = ");
                        lastValueIdx = off.ValueIdx;
                    } else if (lastValueIdx != off.ValueIdx) {
                        writer.WriteLine(";");
                        writer.Write($"__value{off.ValueIdx} = ");
                        lastValueIdx = off.ValueIdx;
                    } else {
                        writer.Write(" | ");
                    }

                    writer.Write($"unchecked(({GetTypeForSize(valueBitSizes[(int)off.ValueIdx])})(unchecked(({GetTypeForSize(field.Size)})p{field.Name}){(off.Shift > 0 ? $" << {off.Shift}" : "")}))");
                    valueShift += off.Size;
                }
            }

            writer.WriteLine(";");

            writer.Indent--;
            writer.WriteLine("}");
        }

        // Implement equality / hashing overloads
        {
            writer.WriteLine();
            writer.WriteLine($"public static bool operator ==({def.SourceType.Name} a, {def.SourceType.Name} b) => a.Equals(b);");
            writer.WriteLine($"public static bool operator !=({def.SourceType.Name} a, {def.SourceType.Name} b) => !a.Equals(b);");

            writer.WriteLine();
            writer.WriteLine($"public bool Equals({def.SourceType.Name} other) {{");
            writer.Indent++;

            for (int i = 0; i < valueIdx; i++) {
                writer.Write(i == 0 ? "return " : " && ");
                writer.Write($"__value{i} == other.__value{i}");
            }
            writer.WriteLine(";");

            writer.Indent--;
            writer.WriteLine("}");

            writer.WriteLine();
            writer.WriteLine($"public override bool Equals(object obj) => obj is {def.SourceType.Name} other && Equals(other);");

            writer.Write("public override string ToString() => $\"{{");
            for (int i = 0; i < def.Fields.Length; i++) {
                if (i != 0) {
                    writer.Write(" ");
                }

                var field = def.Fields[i];
                writer.Write(field.Name);
                writer.Write(":{");
                writer.Write(field.Name);
                writer.Write("}");
            }
            writer.WriteLine("}}\";");

            writer.WriteLine();
            writer.WriteLine("public override int GetHashCode() {");
            writer.Indent++;

            writer.WriteLine("var hash = new System.HashCode();");
            for (int i = 0; i < valueIdx; i++) {
                writer.WriteLine($"hash.Add(__value{i});");
            }
            writer.WriteLine("return hash.ToHashCode();");

            writer.Indent--;
            writer.WriteLine("}");
        }

        while (parentClasses.Count != 0) {
            writer.WriteLine(parentClasses.Pop());
            writer.Indent++;
        }

        // Unwind all scopes
        while (writer.Indent != 0) {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    private static string GetTypeForSize(uint size) {
        return size switch {
            > 32 => "ulong",
            > 16 => "uint",
            > 8 => "ushort",
            _ => "byte"
        };
    }
}
