using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;

namespace BerryUI.SourceGen;

[AttributeUsage(AttributeTargets.Method)]
public sealed class MultiArraySortAttribute(params Type[] types) : Attribute;

[Generator]
public class MultiArraySortGenerator {
    private const string MultiArraySortAttributeName = $"BerryUI.SourceGen.{nameof(MultiArraySortAttribute)}";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var sources = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MultiArraySortAttributeName,
                predicate: IsSyntaxTargetForGeneration,
                transform: GetSemanticTargetForGeneration)
            .Collect();

        context.RegisterSourceOutput(sources, static (context, sources) => {
            using var sw = new StringWriter();
            using var writer = new IndentedTextWriter(sw);

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System.Runtime.InteropServices;");
            writer.WriteLine("using System.Runtime.CompilerServices;");
            writer.WriteLine();

            foreach (var source in sources) {
                Generate(source, writer);
            }

            context.AddSource("MultiArraySort.g.cs", sw.ToString());
        });
    }

    private readonly struct Definition(TypeDefinition sourceType, string[] targetTypes) : IEquatable<Definition> {
        public readonly TypeDefinition SourceType = sourceType;
        public readonly string[] TargetTypes = targetTypes;

        public bool Equals(Definition other) {
            if (SourceType != other.SourceType) {
                return false;
            }
            if (!TargetTypes.SequenceEqual(other.TargetTypes)) {
                return false;
            }
            return true;
        }
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken ct) {
        return node is MethodDeclarationSyntax;
    }

    private static Definition GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
        var methodDecl = (MethodDeclarationSyntax)ctx.TargetNode;
        var methodSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        return new Definition(
            sourceType: TypeDefinition.FromSymbol(methodSymbol, (TypeDeclarationSyntax)methodDecl.Parent!),
            targetTypes: ctx.Attributes
                .Where(arg =>
                    arg.AttributeClass?.Name == nameof(MultiArraySortAttribute) &&
                    arg.AttributeClass?.ToDisplayString() == MultiArraySortAttributeName)
                .SelectMany(arg => arg.ConstructorArguments[0].Values)
                .Select(entry => ((INamedTypeSymbol)entry.Value!).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToArray()
            );
    }

    private static void Generate(Definition def, IndentedTextWriter writer) {
        // Emit the namespace.
        if (!string.IsNullOrWhiteSpace(def.SourceType.Namespace)) {
            writer.WriteLine($"namespace {def.SourceType.Namespace} {{");
            writer.Indent++;
        }

        // Emit containing types.
        var parentClasses = new Stack<string>();
        var parent = def.SourceType.Parent;
        while (parent is not null) {
            parentClasses.Push($"partial {parent.Keyword} {parent.Name} {{");
            parent = parent.Parent;
        }
        while (parentClasses.Count != 0) {
            writer.WriteLine(parentClasses.Pop());
            writer.Indent++;
        }

        // Unwind all scopes
        while (writer.Indent != 0) {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
