using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;

namespace BerryUI.SourceGen;

#pragma warning disable CS9113 // Parameter is unread.

/// Declares this struct as a (tagged) union.
[AttributeUsage(AttributeTargets.Struct)]
public class UnionAttribute(bool tagged, Type? tagType = null) : Attribute;

/// Specifies that this property should be one possible field of the union.
[AttributeUsage(AttributeTargets.Property)]
public class UnionFieldAttribute : Attribute;

#pragma warning restore CS9113 // Parameter is unread.

[Generator]
public class UnionGenerator : IIncrementalGenerator {
    private const string UnionAttributeName = $"BerryUI.SourceGen.{nameof(UnionAttribute)}";
    private const string UnionFieldAttributeName = $"BerryUI.SourceGen.{nameof(UnionFieldAttribute)}";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var sources = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                UnionAttributeName,
                predicate: IsSyntaxTargetForGeneration,
                transform: GetSemanticTargetForGeneration)
            .Collect();

        context.RegisterSourceOutput(sources, static (context, sources) => {
            using var sw = new StringWriter();
            using var writer = new IndentedTextWriter(sw);

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System.Runtime.InteropServices;");
            writer.WriteLine("using System.Runtime.CompilerServices;");
            writer.WriteLine();

            foreach (var source in sources) {
                foreach (var field in source.Fields) {
                    if (field.Location == null) {
                        continue;
                    }

                    context.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor(
                        id: "BERRYUI0001",
                        title: "Managed type inside union",
                        description: "Managed types are not allowed inside unions.",
                        messageFormat: "Managed types are not allowed inside unions, since the runtime doesn't support it.",
                        category: "Usage",
                        defaultSeverity: DiagnosticSeverity.Error,
                        isEnabledByDefault: true
                    ), field.Location));
                }

                Generate(source, writer);
            }

            context.AddSource("Unions.g.cs", sw.ToString());
        });
    }

    private readonly struct Definition(TypeDefinition sourceType, Definition.Field[] fields, bool tagged, string? tagType) : IEquatable<Definition> {
        public readonly struct Field(string type, string name, uint size, uint align, string modifiers, Location? location) : IEquatable<Field> {
            public readonly string Type = type;
            public readonly string Name = name;
            public readonly uint Size = size;
            public readonly uint Align = align;
            public readonly string Modifiers = modifiers;

            public readonly Location? Location = location;

            public bool Equals(Field other) =>
                Type == other.Type &&
                Name == other.Name &&
                Size == other.Size &&
                Align == other.Align &&
                Modifiers == other.Modifiers;
        }

        public readonly TypeDefinition SourceType = sourceType;
        public readonly Field[] Fields = fields;
        public readonly bool IsTagged = tagged;
        public readonly string? TagType = tagType;

        public bool Equals(Definition other) =>
            SourceType.Equals(other.SourceType) &&
            Fields.SequenceEqual(other.Fields) &&
            IsTagged == other.IsTagged &&
            TagType == other.TagType;
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken ct) {
        return node is StructDeclarationSyntax;
    }

    private static Definition GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
        var typeDecl = (TypeDeclarationSyntax)ctx.TargetNode;
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        return new Definition(
            sourceType: TypeDefinition.FromSymbol(typeSymbol, typeDecl),
            fields: typeSymbol
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Select(property => {
                    if (!property
                        .GetAttributes()
                        .Any(attr => attr.AttributeClass?.ToDisplayString() == UnionFieldAttributeName)
                    ) {
                        return new Definition.Field("", "", 0, 0, "", null);
                    }

                    string modifiers = "";
                    var propertyDecl = (PropertyDeclarationSyntax?) property.DeclaringSyntaxReferences
                        .Select(r => r.GetSyntax(ct))
                        .FirstOrDefault(n => n is PropertyDeclarationSyntax);
                    if (propertyDecl is not null) {
                        modifiers = string.Join(" ", propertyDecl.Modifiers
                            .Where(t => !t.IsKind(SyntaxKind.PartialKeyword))
                            .Select(t => t.Text));
                    }

                    bool invalid = !property.Type.CalcUnmanaged(out uint size, out uint align);
                    return new Definition.Field(
                        type: property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        property.Name,
                        size,
                        align,
                        modifiers: modifiers,
                        invalid ? property.Locations[0] : null);
                })
                .Where(def => !string.IsNullOrEmpty(def.Type))
                .ToArray(),
            tagged: ctx.Attributes
                .Where(arg =>
                    arg.AttributeClass?.Name == nameof(UnionAttribute) &&
                    arg.AttributeClass?.ToDisplayString() == UnionAttributeName)
                .Select(arg => (bool)arg.ConstructorArguments[0].Value!)
                .First(),
            tagType: ctx.Attributes
                .Where(arg =>
                    arg.AttributeClass?.Name == nameof(UnionAttribute) &&
                    arg.AttributeClass?.ToDisplayString() == UnionAttributeName)
                .Select(arg => {
                    var type = (INamedTypeSymbol?)arg.ConstructorArguments[1].Value;
                    return type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                })
                .First()
            );
    }

    private static void Generate(Definition def, IndentedTextWriter writer) {
        // Emit the namespace.
        if (!string.IsNullOrWhiteSpace(def.SourceType.Namespace)) {
            writer.WriteLine($"namespace {def.SourceType.Namespace} {{");
            writer.Indent++;
        }

        // Emit containing types.
        var parentClasses = new Stack<string>();
        var parent = def.SourceType.Parent;
        while (parent is not null) {
            parentClasses.Push($"partial {parent.Keyword} {parent.Name} {{");
            parent = parent.Parent;
        }
        while (parentClasses.Count != 0) {
            writer.WriteLine(parentClasses.Pop());
            writer.Indent++;
        }

        // Emit the type definition
        writer.WriteLine("[StructLayout(LayoutKind.Explicit, Pack = 1)]");
        writer.WriteLine($"partial {def.SourceType.Keyword} {def.SourceType.Name} {{");
        writer.Indent++;

        if (def is { IsTagged: true, TagType: null }) {
            // Generate the tag enum
            writer.WriteLine("private enum Tag {");
            writer.Indent++;

            foreach (var entry in def.Fields) {
                writer.WriteLine($"{entry.Name},");
            }

            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Add active tag
        if (def.IsTagged) {
            writer.WriteLine($"[FieldOffset({def.Fields.Select(e => e.Size).Max() + 1})]");
            writer.WriteLine($"private {def.TagType ?? "Tag"} __active;");
            writer.WriteLine($"public {def.TagType ?? "Tag"} Active {{");
            writer.Indent++;

            writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            writer.WriteLine("get => __active;");

            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
        }

        // Generate the backing fields
        foreach (var field in def.Fields) {
            writer.WriteLine("[FieldOffset(0)]");
            writer.WriteLine($"private {field.Type} __{field.Name};");
        }

        // Complete the partial property definitions
        foreach (var field in def.Fields) {
            writer.WriteLine();
            writer.WriteLine($"{field.Modifiers} partial {field.Type} {field.Name} {{");
            writer.Indent++;

            writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            writer.WriteLine("get {");
            writer.Indent++;
            if (def.IsTagged) {
                writer.WriteLine($"System.Diagnostics.Debug.Assert(__active == {def.TagType ?? "Tag"}.{field.Name}, $\"Tried to access tagged union field '{field.Name}' while '{{__active}}' was active.\");");
            }
            writer.WriteLine($"return __{field.Name};");
            writer.Indent--;
            writer.WriteLine("}");

            writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            writer.WriteLine("set {");
            writer.Indent++;
            if (def.IsTagged) {
                writer.WriteLine($"__active = {def.TagType ?? "Tag"}.{field.Name};");
            }
            writer.WriteLine($"__{field.Name} = value;");
            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");
        }

        // Provide implicit conversions
        foreach (var field in def.Fields) {
            writer.WriteLine();
            writer.WriteLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            writer.WriteLine($"{field.Modifiers} static implicit operator {def.SourceType.Name}({field.Type} p{field.Name}) {{");
            writer.Indent++;

            writer.WriteLine($"Unsafe.SkipInit(out {def.SourceType.Name} value);");
            if (def.IsTagged) {
                writer.WriteLine($"value.__active = {def.TagType ?? "Tag"}.{field.Name};");
            }
            writer.WriteLine($"value.__{field.Name} = p{field.Name};");
            writer.WriteLine("return value;");

            writer.Indent--;
            writer.WriteLine("}");
        }

        // Unwind all scopes
        while (writer.Indent != 0) {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }
}
