name: Build Native Libraries

on:
  push:
    paths:
      - .github/workflows/build-native.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ZLIB_VERSION: 1.3.1
  LIBPNG_VERSION: 1.6.58
  FREETYPE_VERSION: 2.14.3
  GRAPHITE2_VERSION: 1.3.15
  HARFBUZZ_VERSION: 14.3.1
  SDL3_VERSION: 3.4.14
  FNA_VERSION: 26.08
  
  MESON_BUILD_TYPE: release
  CMAKE_BUILD_TYPE: Release

jobs:
  build-native:
    strategy:
      matrix:
        include:
          - name: Windows x86
            os: windows-latest
            platform: windows
            msys2_system: mingw32
            msys2_env: i686
            # Avoid dependency on Visual C++ Redistributable
            cmake_flags: >-
              -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
            meson_flags: >-
              -Db_vscrt=static_from_buildtype

          - name: Windows x64
            os: windows-latest
            platform: windows
            msys2_system: mingw64
            msys2_env: x86_64
            # Avoid dependency on Visual C++ Redistributable
            cmake_flags: >-
              -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>"
            meson_flags: >-
              -Db_vscrt=static_from_buildtype

          - name: Linux x64
            os: ubuntu-latest
            platform: linux
            # Use musl to avoid dependency on modern glibc version
            container: alpine:latest
            cmake_flags: >-
              -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed"
              -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed"
              -DCMAKE_C_STANDARD_LIBRARIES="/usr/lib/libc.a -lgcc"
            meson_flags: >-
              -Db_staticpic=true
              -Dc_link_args="-Wl,--as-needed /usr/lib/libc.a -lgcc"

          - name: macOS x64
            os: macos-15-intel
            platform: macos

    name: Native Libraries (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    env:
      # Keep support for old macOS versions
      MACOSX_DEPLOYMENT_TARGET: 10.12

    defaults:
      run:
        shell: sh

    steps:
      # Setup
      - name: Set up MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.platform == 'windows' }}
        with:
          arch: ${{ matrix.msys2_env == 'x86_64' && 'x64' || 'x86' }}

      # See https://github.com/ilammy/msvc-dev-cmd#caveats
      - name: Remove GNU link.exe (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: rm /usr/bin/link

      - name: Set up MSYS2 (Windows)
        uses: msys2/setup-msys2@v2
        if: ${{ matrix.platform == 'windows' }}
        with:
          msystem: ${{ matrix.msys2_system }}
          install: >-
            mingw-w64-${{ matrix.msys2_env }}-cc
            mingw-w64-${{ matrix.msys2_env }}-make

      - name: Set up Python (Windows)
        uses: actions/setup-python@v5
        if: ${{ matrix.platform == 'windows' }}
        with:
          python-version: '3.x'

      - name: Install dependencies (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: |
          python -m pip install cmake meson ninja
          choco install pkgconfiglite -y
      
      - name: Install dependencies (macOS)
        if: ${{ matrix.platform == 'macos' }}
        run: brew install meson

      - name: Install dependencies (Linux)
        if: ${{ matrix.platform == 'linux' }}
        run: apk add --no-cache musl-dev g++ make cmake ninja meson pkgconfig git curl
      
      - name: Create install prefix
        run: |
          mkdir -p prefix
          echo "PREFIX=$(pwd)/prefix" >> $GITHUB_ENV
      
      # zlib
      - name: Build zlib
        run: |
          curl -O -L https://github.com/madler/zlib/releases/download/v${{ env.ZLIB_VERSION }}/zlib-${{ env.ZLIB_VERSION }}.tar.gz
          tar xzf zlib-${{ env.ZLIB_VERSION }}.tar.gz
          cd zlib-${{ env.ZLIB_VERSION }}
          
          # Avoid installing a shared library
          if [ "x${{ runner.os }}" = "xmacOS" ]; then
            sed -i'' -e 's/install(TARGETS zlib zlibstatic/install(TARGETS zlibstatic/' CMakeLists.txt
          else
            sed -i 's/install(TARGETS zlib zlibstatic/install(TARGETS zlibstatic/' CMakeLists.txt
          fi
          
          cmake -B build -G Ninja \
            -DINSTALL_PKGCONFIG_DIR=${{ env.PREFIX }}/lib/pkgconfig \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}
          
      # libpng
      - name: Build libpng
        run: |
          curl -O -L https://sourceforge.net/projects/libpng/files/libpng16/${{ env.LIBPNG_VERSION }}/libpng-${{ env.LIBPNG_VERSION }}.tar.gz
          tar xzf libpng-${{ env.LIBPNG_VERSION }}.tar.gz
          cd libpng-${{ env.LIBPNG_VERSION }}
          
          cmake -B build -G Ninja \
            -DPNG_SHARED=OFF \
            -DPNG_STATIC=ON \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}

      # FreeType
      - name: Build FreeType
        run: |
          curl -O -L https://sourceforge.net/projects/freetype/files/freetype2/${{ env.FREETYPE_VERSION }}/freetype-${{ env.FREETYPE_VERSION }}.tar.gz
          tar xzf freetype-${{ env.FREETYPE_VERSION }}.tar.gz
          cd freetype-${{ env.FREETYPE_VERSION }}
          
          cmake -B build -G Ninja \
            -DFT_DISABLE_BZIP2=TRUE \
            -DFT_DISABLE_BROTLI=TRUE \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}

      # Graphite2
      - name: Build Graphite2
        run: |
          curl -O -L https://github.com/silnrsi/graphite/releases/download/${{ env.GRAPHITE2_VERSION }}/graphite2-${{ env.GRAPHITE2_VERSION }}.tgz
          tar xzf graphite2-${{ env.GRAPHITE2_VERSION }}.tgz
          cd graphite2-${{ env.GRAPHITE2_VERSION }}
          
          cmake -B build -G Ninja \
            -DGRAPHITE2_NFILEFACE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Create pkg-config entries (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: |
          WIN_PREFIX="$(cygpath -w "${{ env.PREFIX }}" | sed 's#\\#/#g')"

          # zlib
          cat > "${{ env.PREFIX }}/lib/pkgconfig/zlib.pc" <<EOF
          prefix=$WIN_PREFIX
          exec_prefix=\${prefix}
          libdir=\${exec_prefix}/lib
          includedir=\${prefix}/include

          Name: zlib
          Description: zlib compression library
          Version: 1.3.1

          Libs: "\${libdir}/zlibstatic.lib"
          Cflags: -I"\${includedir}"
          EOF

          # libpng
          cat > "${{ env.PREFIX }}/lib/pkgconfig/libpng.pc" <<EOF
          prefix=$WIN_PREFIX
          exec_prefix=\${prefix}
          libdir=\${exec_prefix}/lib
          includedir=\${prefix}/include/libpng16

          Name: libpng
          Description: Loads and saves PNG files
          Version: 1.6.58
          Requires.private: zlib
          Libs: "\${libdir}/libpng16_static.lib"
          Libs.private: "\${libdir}/zlibstatic.lib"
          Cflags: -I"\${includedir}"
          EOF
          
          # Graphite2
          cat > "${{ env.PREFIX }}/lib/pkgconfig/graphite2.pc" <<EOF
          prefix=$WIN_PREFIX
          exec_prefix=\${prefix}
          libdir=\${exec_prefix}/lib
          includedir=\${prefix}/include

          Name: Graphite2
          Description: Font rendering engine for Complex Scripts
          Version: 3.3.1
          Libs: "\${libdir}/graphite2.lib"
          Cflags: -I"\${includedir}" -DGRAPHITE2_STATIC
          EOF

      # HarfBuzz
      - name: Build HarfBuzz
        run: |
          curl -O -L https://github.com/harfbuzz/harfbuzz/releases/download/${{ env.HARFBUZZ_VERSION }}/harfbuzz-${{ env.HARFBUZZ_VERSION }}.tar.xz
          tar xJf harfbuzz-${{ env.HARFBUZZ_VERSION }}.tar.xz
          cd harfbuzz-${{ env.HARFBUZZ_VERSION }}

          # Additional libraries may be enabled as needed
          meson setup build \
            --prefix=${{ env.PREFIX }}  \
            --pkg-config-path ${{ env.PREFIX }}/lib/pkgconfig \
            --prefer-static \
            -Dtests=disabled \
            -Dutilities=disabled \
            -Draster=disabled \
            -Dvector=disabled \
            -Dgpu=disabled \
            -Dsubset=disabled \
            -Dglib=disabled \
            -Dgobject=disabled \
            -Dcairo=disabled \
            -Dicu=disabled \
            -Dgraphite2=enabled \
            -Dfreetype=enabled \
            -Dbuildtype=${{ env.MESON_BUILD_TYPE }} \
             ${{ matrix.meson_flags }}

          ninja -C build install

          if [ "x${{ runner.os }}" = "xmacOS" ]; then
            # Fix Meson embedding an absolute ID path
            install_name_tool -id "@rpath/libharfbuzz.0.dylib" ${{ env.PREFIX }}/lib/libharfbuzz.0.dylib
          fi

          
      # SDL3
      - name: Install SDL3 dependencies (Linux)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          # See https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/sdl3/APKBUILD#L10-31
          apk add --no-cache \
            alsa-lib-dev eudev-dev jack-dev libdecor-dev libsamplerate-dev libusb-dev \
            libx11-dev libxcursor-dev libxext-dev libxkbcommon-dev libxrandr-dev libxrender-dev libxscrnsaver-dev libxtst-dev \
            pipewire-dev pulseaudio-dev samurai wayland-dev wayland-protocols
      
      - name: Build SDL3
        run: |
          curl -O -L https://github.com/libsdl-org/SDL/releases/download/release-${{ env.SDL3_VERSION }}/SDL3-${{ env.SDL3_VERSION }}.tar.gz
          tar xzf SDL3-${{ env.SDL3_VERSION }}.tar.gz
          cd SDL3-${{ env.SDL3_VERSION }}
          
          cmake -B build -G Ninja \
            -DSDL_VENDOR_INFO="GitHub Workflow" \
            -DSDL_CMAKE_DEBUG_POSTFIX="" \
            -DSDL_FORCE_STATIC_VCRT=ON \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}
      
      # FNA3D
      - name: Build FNA3D
        run: |
          git clone --recursive --depth=1 https://github.com/FNA-XNA/FNA3D.git --branch ${{ env.FNA_VERSION }}
          cd FNA3D
          
          if [ "x${{ runner.os }}" = "xWindows" ]; then
            # Update CMake to use CMAKE_MSVC_RUNTIME_LIBRARY
            sed -i 's/cmake_minimum_required.*/cmake_minimum_required(VERSION 3.16)/' CMakeLists.txt
          fi
          
          cmake -B build -G Ninja \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}
      
      # FAudio
      - name: Build FAudio
        run: |
          git clone --recursive --depth=1 https://github.com/FNA-XNA/FAudio.git --branch ${{ env.FNA_VERSION }}
          cd FAudio
          
          if [ "x${{ runner.os }}" = "xWindows" ]; then
            # Update CMake to use CMAKE_MSVC_RUNTIME_LIBRARY
            sed -i 's/cmake_minimum_required.*/cmake_minimum_required(VERSION 3.16)/' CMakeLists.txt
          fi
          
          cmake -B build -G Ninja \
            -DCMAKE_PREFIX_PATH=${{ env.PREFIX }} \
            -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
             ${{ matrix.cmake_flags }}
          
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }}
          cmake --install build --config ${{ env.CMAKE_BUILD_TYPE }}

      # Theorafile
      - name: Fetch Theorafile
        run: git clone --recursive --depth=1 https://github.com/FNA-XNA/Theorafile.git
      
      - name: Build Theorafile (Windows)
        if: ${{ matrix.platform == 'windows' }}
        working-directory: Theorafile
        shell: msys2 {0}
        run: mingw32-make

      - name: Build Theorafile (macOS)
        if: ${{ matrix.platform == 'macos' }}
        working-directory: Theorafile
        run: make
        
      - name: Build Theorafile (Linux)
        if: ${{ matrix.platform == 'linux' }}
        working-directory: Theorafile
        run: make LDFLAGS="/usr/lib/libc.a -lgcc"

      # Upload
      - name: Copy binaries (Windows)
        if: ${{ matrix.platform == 'windows' }}
        run: |
          cp ${{ env.PREFIX }}/bin/freetype.dll freetype.dll
          cp ${{ env.PREFIX }}/bin/harfbuzz.dll harfbuzz.dll
          cp ${{ env.PREFIX }}/bin/SDL3.dll SDL3.dll
          cp ${{ env.PREFIX }}/bin/FNA3D.dll FNA3D.dll
          cp ${{ env.PREFIX }}/bin/FAudio.dll FAudio.dll
          cp Theorafile/libtheorafile.dll libtheorafile.dll

      - name: Copy binaries (macOS)
        if: ${{ matrix.platform == 'macos' }}
        run: |
          cp ${{ env.PREFIX }}/lib/libfreetype.6.dylib libfreetype.6.dylib
          cp ${{ env.PREFIX }}/lib/libharfbuzz.0.dylib libharfbuzz.0.dylib
          cp ${{ env.PREFIX }}/lib/libSDL3.dylib libSDL3.dylib
          cp ${{ env.PREFIX }}/lib/libFNA3D.0.dylib libFNA3D.0.dylib
          cp ${{ env.PREFIX }}/lib/libFAudio.0.dylib libFAudio.0.dylib
          cp Theorafile/libtheorafile.dylib libtheorafile.dylib

      - name: Copy binaries (Linux)
        if: ${{ matrix.platform == 'linux' }}
        run: |
          cp ${{ env.PREFIX }}/lib/libfreetype.so.6 libfreetype.so.6
          cp ${{ env.PREFIX }}/lib/libharfbuzz.so.0 libharfbuzz.so.0
          cp ${{ env.PREFIX }}/lib/libSDL3.so.0 libSDL3.so.0
          cp ${{ env.PREFIX }}/lib/libFNA3D.so.0 libFNA3D.so.0
          cp ${{ env.PREFIX }}/lib/libFAudio.so.0 libFAudio.so.0
          cp Theorafile/libtheorafile.so libtheorafile.so

      - name: Upload Artifacts (Windows)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.platform == 'windows' }}
        with:
          name: native-windows-${{ matrix.msys2_env }}
          path: |
            freetype.dll
            harfbuzz.dll
            SDL3.dll
            FNA3D.dll
            FAudio.dll
            libtheorafile.dll

      - name: Upload Artifacts (macOS)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.platform == 'macos' }}
        with:
          name: native-macos-x86_64
          path: |
            libfreetype.6.dylib
            libharfbuzz.0.dylib
            libSDL3.0.dylib
            libFNA3D.0.dylib
            libFAudio.0.dylib
            libtheorafile.dylib

      - name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v7
        if: ${{ matrix.platform == 'linux' }}
        with:
          name: native-linux-x86_64
          path: |
            libfreetype.so.6
            libharfbuzz.so.0
            libSDL3.so.0
            libFNA3D.so.0
            libFAudio.so.0
            libtheorafile.so
            libfmod_SDL.so
